name: Fetch Live YouTube Streams

on:
  schedule:
    - cron: '0 * * * *'   # 每小時執行一次 (UTC)
  workflow_dispatch:       # 支援手動觸發

permissions:
  contents: write          # ✅ 允許 Actions 推送更改

jobs:
  run-php:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Run PHP script
      run: php fetch_live.php

    - name: Commit output file
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git pull --rebase origin main
        git add live_links.txt
        git commit -m "Update live_links.txt - $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push origin main
