name: Update Live URLs

on:
  schedule:
    - cron: '0 */2 * * *'  # 每兩小時執行一次
  workflow_dispatch:       # 支援手動觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Run PHP script
      run: php check_live.php

    - name: Commit and force-push live URLs
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        # 只提交最新的 live_urls.txt（內容為正在直播的網址）
        git add live_urls.txt
        git commit -m "Update live URLs" || echo "No live URLs to commit"

        # 直接強制推送，覆蓋遠端 main 分支
        git push --force https://x-access-token:${REPO_TOKEN}@github.com/${{ github.repository }}.git main
